import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex justify-center items-center py-5 bg-black text-white">
          <li className="mr-5"><Link href={'/'}>Home</Link></li>
          <li className="mr-5"><Link href={'/about'}>About</Link></li>
          <li className=""><Link href={'/login'}>Login</Link></li>
        </ul>
        {children}
      </body>
    </html>
  );
}
